{% set version = "2.2.1" %}

package:
  name: bob.db.iris
  version: {{ version }}

source:
  fn: bob.db.iris-{{ version }}.zip
  md5: e1a8c8601b34eb73776519f5f3787e47
  url: https://pypi.io/packages/source/b/bob.db.iris/bob.db.iris-{{ version }}.zip

build:
  entry_points:
    - iris_lda.py = bob.db.iris.example.lda:main
  number: 0
  skip: true  # [win]
  script: python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - bob.io.base
    - bob.measure
    - bob.learn.linear
    - bob.db.base
    - matplotlib

  run:
    - python
    - bob.io.base
    - bob.measure
    - bob.learn.linear
    - bob.db.base
    - matplotlib

test:
  commands:
    - iris_lda.py --help
    - nosetests -sv bob.db.iris

  imports:
    - bob
    - bob.db
    - bob.db.iris
    - bob.db.iris.example

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: Modified BSD License (3-clause)
  summary: Bob access API for Fisher's Iris Flower Dataset

extra:
  recipe-maintainers:
    - 183amir
